version: '3.9'

services:
  db:
    image: postgres:16
    container_name: todoit_db
    restart: always
    environment:
      POSTGRES_USER: todoit_user
      POSTGRES_PASSWORD: todoit_pass
      POSTGRES_DB: todoit_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
