services:
  - type: web
    name: todo-app-backend
    runtime: node
    plan: free
    region: oregon

    buildCommand: bun install && bun x prisma generate
    startCommand: bun run server.ts

    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: todo-app-db
          property: connectionString

databases:
  - name: todo-app-db
    databaseName: todo_app
    plan: free
    region: oregon
